stages:
  - build

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - ./gradlew build publish --info --no-daemon
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 days
  only:
    - master
  tags:
    - linux
