modLoader = "javafml" #mandatory
loaderVersion = "${loader_version_range}" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "${mod_license}"

[[mods]] #mandatory
modId = "${mod_id}" #mandatory
logoFile = "unifyeverything_logo.png"
version = "${mod_version}" #mandatory
displayName = "${mod_name}" #mandatory
authors = "${mod_authors}" #optional
updateJSONURL = "https://git.karmakrafts.dev/kk/mc-projects/almost-unify-everything/-/raw/master/versions.json?ref_type=heads"
description = '''${mod_description}'''
credits = """
"""

[[dependencies.${ mod_id }]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "${forge_version_range}" #mandatory
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[modproperties.${ mod_id }]
catalogueImageIcon = "unifyeverything_logo.png"